<?php
namespace Marcosado\BlockBuilder;

if ( ! defined( 'ABSPATH' ) ) { exit; }

class Marcosado_Renderer
{
    /**
     * Rendu d'un bloc par son slug, avec les attributs donnés.
     * Gère la vérification du fichier physique, sa recréation si manquant,
     * et l'inclusion PHP propre.
     */
    public static function render(string $slug, array $attributes): string
    {
        $blocks_dir = MARCOSADO_PLUGIN_DIR . 'blocks/';
        $file_path  = $blocks_dir . sanitize_key($slug) . '.php';

        // Si le fichier n'existe pas (ex: après migration), on le recrée depuis la DB
        if (!file_exists($file_path)) {
            self::regenerate_file($slug, $blocks_dir, $file_path);
        }

        // Extraction propre pour que les variables soient dispos dans le bloc
        extract($attributes, EXTR_SKIP);
        
        ob_start();
        if (file_exists($file_path)) {
            include $file_path;
        } else {
            // Fallback ultime en cas de problème de droits d'écriture
            echo "<!-- Erreur : Impossible de lire ou créer le fichier du bloc " . esc_html($slug) . " -->";
        }
        return ob_get_clean();
    }

    /**
     * Recrée le fichier physique depuis la base de données
     */
    private static function regenerate_file(string $slug, string $blocks_dir, string $file_path): void
    {
        global $wpdb;
        
        // On récupère le code du bloc depuis la DB
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
        $row = $wpdb->get_row($wpdb->prepare(
            "SELECT name, code FROM {$wpdb->prefix}marcosado_blocks WHERE slug = %s",
            $slug
        ));

        if ($row && !empty($row->code)) {
            if (!file_exists($blocks_dir)) {
                wp_mkdir_p($blocks_dir); // wp_mkdir_p gère les droits correctement
            }

            // Génération de l'en-tête (optionnel mais propre)
            $header = "<?php\n// phpcs:disable\nif ( ! defined( 'ABSPATH' ) ) exit;\n/**\n * Block Name: " . $row->name . "\n * Auto-generated by BlockMaster.\n */\n?>\n";
            
            $written = file_put_contents($file_path, $header . $row->code);

            if ($written !== false && function_exists('opcache_invalidate')) {
                opcache_invalidate($file_path, true);
            }
        }
    }
}
